config/routes.rb
OilWells::Application.routes.draw do
  root :to => "wells#index"
  resources :wells do
    resources :operators, :only => [:show]
    resources :leases, :only => [:show]
  end

  resources :operators do
    resources :wells, :only => [:show]
    resources :leases, :only => [:show]
  end

  resources :leases do
    resources :wells, :only => [:show]
    resources :operators, :only => [:show]
  end

  

end

app/models/well.rb
class Well < ActiveRecord::Base
  has_many :operator_wells
  has_many :operators, :through => :operator_wells

  has_many :lease_wells
  has_many :leases, :through => :lease_wells

  validates :tracking_number, uniqueness: true, presence: true, :length => { :is => 5 }
end

app/controllers/wells_controller.rb
class WellsController < ApplicationController
  before_action :set_well, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /wells
  # GET /wells.json
  def index
    @wells = Well.order(sort_column + " " + sort_direction + " NULLS LAST").paginate(:per_page => 50, :page => params[:page])
  end

  # GET /wells/1
  # GET /wells/1.json
  def show
  end

  # GET /wells/new
  def new
    @well = Well.new
  end

  # GET /wells/1/edit
  def edit
  end

  # POST /wells
  # POST /wells.json
  def create
    @well = Well.new(well_params)

    respond_to do |format|
      if @well.save
        format.html { redirect_to @well, notice: 'Well was successfully created.' }
        format.json { render action: 'show', status: :created, location: @well }
      else
        format.html { render action: 'new' }
        format.json { render json: @well.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wells/1
  # PATCH/PUT /wells/1.json
  def update
    respond_to do |format|
      if @well.update(well_params)
        format.html { redirect_to @well, notice: 'Well was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @well.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wells/1
  # DELETE /wells/1.json
  def destroy
    @well.destroy
    respond_to do |format|
      format.html { redirect_to wells_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_well
      @well = Well.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def well_params
      params.require(:well).permit(:tracking_number, :api_number, :operator_name)
    end

  # This method is set up to provide a default to the column sorting if the params hash is empty. From railscast 228.
  def sort_column
    if Well.column_names.include?(params[:sort]) then
      params[:sort]
    else
      "submit_date"
    end
  end

  # This method is set up to provide a default to the column sorting if the params hash is empty. From railscast 228.
  def sort_direction
    if %w[asc desc].include?(params[:direction]) then
      params[:direction]
    else
      "desc"
    end
  end


end

app/helpers/wells_helper.rb
module WellsHelper
end

app/views/wells/_form.html.erb
<%= form_for(@well) do |f| %>
  <% if @well.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@well.errors.count, "error") %> prohibited this well from being saved:</h2>

      <ul>
      <% @well.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tracking_number %><br>
    <%= f.text_field :tracking_number %>
  </div>
  <div class="field">
    <%= f.label :api_number %><br>
    <%= f.text_field :api_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wells/edit.html.erb
<h1>Editing well</h1>

<%= render 'form' %>

<%= link_to 'Show', @well %> |
<%= link_to 'Back', wells_path %>

app/views/wells/index.html.erb
<h1>Listing wells</h1>
Well Count: <%= @wells.count %>
<table>
  <thead>
    <tr>
      <th>Tracking number</th>
      <th>Api number</th>
      <th>Operator name</th>
      <th><%= sortable "submit_date", "Submit Date" %></th>
      <th>Well Number</th>
      <th>Lease Name</th>
      <th>Lease Number</th>
      <th>Packet Type</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @wells.each do |well| %>
      <tr>
        <td><%= link_to well.tracking_number, "http://webapps.rrc.state.tx.us/CMPL/viewPdfReportFormAction.do?method=cmplW2FormPdf&packetSummaryId=#{well.tracking_number}" %></td>
        <td><%= well.api_number %></td>
        <td><%= link_to well.operators.pluck(:name).join(", ").try(:titleize), operator_path(well.operators.pluck(:id)) %></td>
        <td><%= well.submit_date %></td>
        <td><%= well.well_number %></td>
        <td><%= well.leases.pluck(:name).join(", ").try(:titleize) %></td>
        <td><%= well.leases.pluck(:lease_number).join(", ") %></td>
        <td><%= well.packet_type %></td>
        <td><%= link_to 'Show', well %></td>
        <td><%= link_to 'Edit', edit_well_path(well) %></td>
        <td><%= link_to 'Destroy', well, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @wells %>
<br>

<%= link_to 'New Well', new_well_path %>

app/views/wells/new.html.erb
<h1>New well</h1>

<%= render 'form' %>

<%= link_to 'Back', wells_path %>

app/views/wells/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tracking number:</strong>
  <%= @well.tracking_number %>
</p>

<p>
  <strong>Api number:</strong>
  <%= @well.api_number %>
</p>

<p>
  <strong>Operator name:</strong>
  <%= @well.operators.name %>
</p>

<%= link_to 'Edit', edit_well_path(@well) %> |
<%= link_to 'Back', wells_path %>