config/routes.rb
OilWells::Application.routes.draw do
  root :to => "wells#index"
  resources :wells do
    resources :operators, :only => [:show]
    resources :leases, :only => [:show]
  end

  resources :operators do
    resources :wells, :only => [:show]
    resources :leases, :only => [:show]
  end

  resources :leases do
    resources :wells, :only => [:show]
    resources :operators, :only => [:show]
  end

  

end

app/models/operator.rb
class Operator < ActiveRecord::Base
  has_many :operator_wells
  has_many :wells, :through => :operator_wells

  has_many :lease_operators
  has_many :leases, :through => :lease_operators

  validates :name, uniqueness: true, presence: true
end

app/controllers/operators_controller.rb
class OperatorsController < ApplicationController
  before_action :set_operator, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /operators
  # GET /operators.json
  def index
    @operators = Operator.paginate(:per_page => 50, :page => params[:page])
  end

  # GET /operators/1
  # GET /operators/1.json
  def show
    @wells = @operator.wells
    @leases = @operator.leases
  end

  # GET /operators/new
  def new
    @operator = Operator.new
  end

  # GET /operators/1/edit
  def edit
  end

  # POST /operators
  # POST /operators.json
  def create
    @operator = Operator.new(operator_params)

    respond_to do |format|
      if @operator.save
        format.html { redirect_to @operator, notice: 'Operator was successfully created.' }
        format.json { render action: 'show', status: :created, location: @operator }
      else
        format.html { render action: 'new' }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operators/1
  # PATCH/PUT /operators/1.json
  def update
    respond_to do |format|
      if @operator.update(operator_params)
        format.html { redirect_to @operator, notice: 'Operator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @operator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operators/1
  # DELETE /operators/1.json
  def destroy
    @operator.destroy
    respond_to do |format|
      format.html { redirect_to operators_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operator
      @operator = Operator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operator_params
      params[:operator]
    end

  # This method is set up to provide a default to the column sorting if the params hash is empty. From railscast 228.
  def sort_column
    if Operator.column_names.include?(params[:sort]) then
      params[:sort]
    else
      "name"
    end
  end

  # This method is set up to provide a default to the column sorting if the params hash is empty. From railscast 228.
  def sort_direction
    if %w[asc desc].include?(params[:direction]) then
      params[:direction]
    else
      "desc"
    end
  end

end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/views/operators/_form.html.erb
<%= form_for(@operator) do |f| %>
  <% if @operator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operator.errors.count, "error") %> prohibited this operator from being saved:</h2>

      <ul>
      <% @operator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operators/edit.html.erb
<h1>Editing operator</h1>

<%= render 'form' %>

<%= link_to 'Show', @operator %> |
<%= link_to 'Back', operators_path %>

app/views/operators/index.html.erb
<h1>Listing Operators</h1>

<table>
  <thead>
    <tr>
      <th><%= sortable "name", "Name" %></th>
      <th>Operator Number</th>
      <th>Wells</th>
      <th>Leases</th>
    </tr>
  </thead>

  <tbody>
    <% @operators.each do |operator| %>
      <tr>
        <td><%= link_to operator.name, operator %></td>
        <td><%= operator.operator_number %></td>
        <td><%= operator.wells.count %></td>
        <td><%= operator.leases.count %></td>
        <td><%= link_to 'Edit', edit_operator_path(operator) %></td>
        <td><%= link_to 'Destroy', operator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table><br>
<%= will_paginate @operators %>
<br>

<%= link_to 'New Operator', new_operator_path %>

app/views/operators/new.html.erb
<h1>New operator</h1>

<%= render 'form' %>

<%= link_to 'Back', operators_path %>

app/views/operators/show.html.erb
<p id="notice"><%= notice %></p>
<strong><%= "Operator Name" %>:</strong>
<%= @operator.name %><br>
<strong><%= "Operator Number" %>:</strong>
<%= @operator.operator_number %><br>
<strong><%= "Wells" %>:</strong>
<%= @operator.wells.count %><br>
<strong><%= "Leases" %>:</strong>
<%= @operator.leases.count %><br><br>


<table>
  <thead>
  <tr>
    <th>Tracking number</th>
    <th>Api number</th>
    <th><%= sortable "submit_date", "Submit Date" %></th>
    <th>Well Number</th>
    <th>Lease Name</th>
    <th>Lease Number</th>
    <th>Packet Type</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @wells.each do |well| %>
      <tr>
        <td><%= link_to well.tracking_number, "http://webapps.rrc.state.tx.us/CMPL/viewPdfReportFormAction.do?method=cmplW2FormPdf&packetSummaryId=#{well.tracking_number}" %></td>
        <td><%= link_to well.api_number, well_path(well) %></td>
        <td><%= well.submit_date %></td>
        <td><%= well.well_number %></td>
        <td><%= well.leases.pluck(:name).join(", ").try(:titleize) %></td>
        <td><%= well.leases.pluck(:lease_number).join(", ") %></td>
        <td><%= well.packet_type %></td>
        <td><%= link_to 'Edit', edit_well_path(well) %></td>
        <td><%= link_to 'Destroy', well, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table><br>


<%= link_to 'Edit', edit_operator_path(@operator) %> |
<%= link_to 'Back', operators_path %>