config/routes.rb
OilWells::Application.routes.draw do
  root :to => "wells#index"
  resources :wells do
    resources :operators, :only => [:show]
    resources :leases, :only => [:show]
  end

  resources :operators do
    resources :wells, :only => [:show]
    resources :leases, :only => [:show]
  end

  resources :leases do
    resources :wells, :only => [:show]
    resources :operators, :only => [:show]
  end

  

end

app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  before_action :set_lease, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  # GET /leases
  # GET /leases.json
  def index
    @leases = Lease.paginate(:per_page => 50, :page => params[:page])
  end

  # GET /leases/1
  # GET /leases/1.json
  def show
    @wells = @lease.wells
    @operators = @lease.operators
  end

  # GET /leases/new
  def new
    @lease = Lease.new
  end

  # GET /leases/1/edit
  def edit
  end

  # POST /leases
  # POST /leases.json
  def create
    @lease = Lease.new(lease_params)

    respond_to do |format|
      if @lease.save
        format.html { redirect_to @lease, notice: 'Lease was successfully created.' }
        format.json { render action: 'show', status: :created, location: @lease }
      else
        format.html { render action: 'new' }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leases/1
  # PATCH/PUT /leases/1.json
  def update
    respond_to do |format|
      if @lease.update(lease_params)
        format.html { redirect_to @lease, notice: 'Lease was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @lease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leases/1
  # DELETE /leases/1.json
  def destroy
    @lease.destroy
    respond_to do |format|
      format.html { redirect_to leases_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lease
      @lease = Lease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lease_params
      params[:lease]
    end

  # This method is set up to provide a default to the column sorting if the params hash is empty. From railscast 228.
  def sort_column
    if Lease.column_names.include?(params[:sort]) then
      params[:sort]
    else
      "name"
    end
  end

  # This method is set up to provide a default to the column sorting if the params hash is empty. From railscast 228.
  def sort_direction
    if %w[asc desc].include?(params[:direction]) then
      params[:direction]
    else
      "desc"
    end
  end

end

app/helpers/leases_helper.rb
module LeasesHelper
end

app/views/leases/_form.html.erb
<%= form_for(@lease) do |f| %>
  <% if @lease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lease.errors.count, "error") %> prohibited this lease from being saved:</h2>

      <ul>
      <% @lease.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leases/edit.html.erb
<h1>Editing lease</h1>

<%= render 'form' %>

<%= link_to 'Show', @lease %> |
<%= link_to 'Back', leases_path %>

app/views/leases/index.html.erb
<h1>Listing leases</h1>

<table>
  <thead>
    <tr>
      <th><%= sortable "lease_name", "Name" %></th>
      <th>Lease Number</th>
      <th>Wells</th>
      <th>Operators</th>
    </tr>
  </thead>

  <tbody>
    <% @leases.each do |lease| %>
      <tr>
        <td><%= link_to lease.name, lease %></td>
        <td><%= lease.lease_number %></td>
        <td><%= lease.wells.count %></td>
        <td><%= lease.operators.count %></td>
        <td><%= link_to 'Edit', edit_lease_path(lease) %></td>
        <td><%= link_to 'Destroy', lease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @leases %>
<br>

<%= link_to 'New Lease', new_lease_path %>

app/views/leases/new.html.erb
<h1>New lease</h1>

<%= render 'form' %>

<%= link_to 'Back', leases_path %>

app/views/leases/show.html.erb
<p id="notice"><%= notice %></p>

<strong><%= "Lease Name" %>:</strong>
<%= @lease.name %><br>
<strong><%= "Lease Number" %>:</strong>
<%= @lease.lease_number %><br>
<strong><%= "Wells" %>:</strong>
<%= @lease.wells.count %><br>
<strong><%= "Operators" %>:</strong>
<%= @lease.operators.count %><br><br>


<table>
  <thead>
  <tr>
    <th>Tracking number</th>
    <th>Api number</th>
    <th>Submit Date</th>
    <th>Well Number</th>
    <th>Packet Type</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @wells.each do |well| %>
      <tr>
        <td><%= link_to well.tracking_number, "http://webapps.rrc.state.tx.us/CMPL/viewPdfReportFormAction.do?method=cmplW2FormPdf&packetSummaryId=#{well.tracking_number}" %></td>
        <td><%= link_to well.api_number, well_path(well) %></td>
        <td><%= well.submit_date %></td>
        <td><%= well.well_number %></td>
        <td><%= well.packet_type %></td>
        <td><%= link_to 'Edit', edit_well_path(well) %></td>
        <td><%= link_to 'Destroy', well, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table><br>


<%= link_to 'Edit', edit_lease_path(@lease) %> |
<%= link_to 'Back', leases_path %>